spring:
  application:
    name: projeto-3
  datasource:
    url: jdbc:postgresql://localhost:5432/anime?createDatabaseIfNotExist=true
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "metrics", "info", "health" ]

